export const LOAD_WEB3 = 'LOAD_WEB3';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const LOAD_CURRENT_ADDRESS = 'LOAD_CURRENT_ADDRESS';
export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS';
export const LOAD_IMAGE = 'LOAD_IMAGE';
export const SET_SEBID = 'SET_SEBID';
export const SET_TABLE_BODY = 'SET_TABLE_BODY';